### ISSUE TITLE
Won't run when using design rule set.

### ISSUE THREAD

**Issue by cwilsontv** [phpmd/phpmd#517]
This one is weird and I didn't see it elsewhere.

When using the design rule set I get an error and it closes. When I remove it, it works fine.

From Circle CI with design:
```
#!/bin/bash -eo pipefail
./vendor/bin/phpmd ./init.php xml cleancode,codesize,controversial,design,unusedcode,naming


Exited with code 1
```
Without design:
```
#!/bin/bash -eo pipefail
./vendor/bin/phpmd ./init.php xml cleancode,codesize,controversial,unusedcode,naming

<?xml version="1.0" encoding="UTF-8" ?>
<pmd version="@project.version@" timestamp="2017-09-06T20:00:17+00:00">
</pmd>
```

Here is my CircleCI script:
```
version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          - v1-dependencies-
      - run: composer install -n --prefer-dist
      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}
      - run: ./vendor/bin/phpmd ./app/addons xml cleancode,codesize,controversial,design,unusedcode,naming
```
composer.json
```
{
    "name": "cwilsontv",
    "description": "phpmd test",
    "authors": [
        {
            "name": "cwilsontv",
            "email": ""
        }
    ],
    "require": {
    },
    "require-dev": {
        "phpmd/phpmd" : "@stable",        
    },
    "autoload": {
        "psr-0": {

        },
        "classmap": [

        ]
    },
    "scripts": {

    }
}
```

Everything is completely barebones, just a file, composer, and phpmd. The php file I point it at doesn't seem to matter either.

Same thing happens locally on two different machines when I run it through the command line, but at least I get a message:
```
C:\src\phpmdtest>php .\vendor\phpmd\phpmd\src\bin\phpmd .\init.php xml naming
<?xml version="1.0" encoding="UTF-8" ?>
<pmd version="@project.version@" timestamp="2017-09-07T14:52:26+00:00">
</pmd>

C:\src\phpmdtest>php .\vendor\phpmd\phpmd\src\bin\phpmd .\init.php xml design
PHP Warning:  file_get_contents(design): failed to open stream: Permission denied in C:\src\phpmdtest\vendor\phpmd\phpmd\src\main\php\PHPMD\RuleSetFactory.php on line 551
PHP Notice:  Trying to get property of non-object in C:\src\phpmdtest\vendor\phpmd\phpmd\src\main\php\PHPMD\RuleSetFactory.php on line 556
```

Not sure how it can be a permission issue for just design, especially since composer installs everything.

Next trouble shooting steps I'll try:
- Use 7.0 instead of 7.1
- Use a ruleset xml to specify the rules to run.
